name: OWASP ZAP DAST

on:
  workflow_dispatch:

permissions:
  security-events: write
  contents: read

jobs:
  zap_scan:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Run ZAP Baseline Scan
        uses: zaproxy/action-baseline@v0.14.0
        with:
          target: 'https://demo.testfire.net'

      - name: Upload Report
        uses: actions/upload-artifact@v4
        with:
          name: zap-report
          path: report_html.html
